name: Advanced CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test on Java ${{ matrix.java }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [17, 21]  # Test on Java 17 and Java 21
      fail-fast: true

    steps:
      # Checkout code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Java (Temurin distribution)
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven  # Automatically caches ~/.m2/repository

      # Verify Java and Maven versions
      - name: Show Java and Maven versions
        run: |
          java -version
          mvn -v

      # Build and run tests with Maven
      - name: Build and test
        run: mvn clean verify -B

      # Upload JUnit test reports
      - name: Upload JUnit test results
        if: always()  # Upload even if tests fail
        uses: actions/upload-artifact@v3.1.2
        with:
          name: junit-test-results
          path: target/surefire-reports/

      # Upload the built JAR artifact
      - name: Upload JAR artifact
        if: success()  # Only upload if build/test succeeded
        uses: actions/upload-artifact@v3.1.2
        with:
          name: todoapp-jar
          path: target/*.jar
